# Site settings
title: SE @ MUICT
email: chaiyong.rag@mahidol.ac.th, morakot.cho@mahidol.ac.th
description: >
  The website of the Software Engineering Research Unit (SERU) at the Faculty of ICT, Mahidol University.
lang: en-US

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://muict-seru.github.io # the base hostname & protocol for your site
git_address: https://github.com/MUICT-SERU
git_edit_address: https://github.com/MUICT-SERU/blob/gh-pages

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: journal # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
